name: deploy-to-roku
on: [push]
jobs:
  deploy-to-roku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'echo "${{ secrets.ID_RSA }}" > id_rsa'
      - run: ls
      - run: chmod 400 ./id_rsa
      - run: ssh -o "StrictHostKeyChecking=no" -i ./id_rsa cicd@18.222.56.243 /home/cicd/pull.sh